import = ["/Users/biubiu/.config/alacritty/dracula.toml", "/Users/biubiu/.config/alacritty/fonts.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[scrolling]
history = 10000
multiplier = 3

[window]
blur = true
decorations = "Buttonless"
dynamic_padding = true
dynamic_title = true
opacity = 0.85
option_as_alt = "Both"
resize_increments = true
startup_mode = "Windowed"

[window.dimensions]
columns = 120
lines = 35
