[colors.primary]
		background: '#282a36'
    foreground: '#f8f8f2'

[colors.cursor]
		text: '#44475a'
    cursor: '#f8f8f2'

[colors.selection]
    text=       '#000000'
    background= '#293334'

  # Normal colors
[colors.normal]
		black:   '#000000'
    red:     '#ff5555'
    green:   '#50fa7b'
    yellow:  '#f1fa8c'
    blue:    '#bd93f9'
    magenta: '#ff79c6'
    cyan:    '#8be9fd'
    white:   '#bfbfbf'

  # Bright colors
[colors.bright]
    black:   '#4d4d4d'
    red:     '#ff6e67'
    green:   '#5af78e'
    yellow:  '#f4f99d'
    blue:    '#caa9fa'
    magenta: '#ff92d0'
    cyan:    '#9aedfe'
    white:   '#e6e6e6'

